# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginForm(object):
    def setupUi(self, loginForm):
        loginForm.setObjectName("loginForm")
        loginForm.resize(217, 242)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(loginForm)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb0 = QtWidgets.QLabel(loginForm)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lb0.setFont(font)
        self.lb0.setAlignment(QtCore.Qt.AlignCenter)
        self.lb0.setObjectName("lb0")
        self.verticalLayout.addWidget(self.lb0)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb1 = QtWidgets.QLabel(loginForm)
        self.lb1.setObjectName("lb1")
        self.horizontalLayout.addWidget(self.lb1)
        self.username = QtWidgets.QLineEdit(loginForm)
        self.username.setObjectName("username")
        self.horizontalLayout.addWidget(self.username)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb2 = QtWidgets.QLabel(loginForm)
        self.lb2.setObjectName("lb2")
        self.horizontalLayout_2.addWidget(self.lb2)
        self.password = QtWidgets.QLineEdit(loginForm)
        self.password.setObjectName("password")
        self.horizontalLayout_2.addWidget(self.password)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb3 = QtWidgets.QLabel(loginForm)
        self.lb3.setObjectName("lb3")
        self.horizontalLayout_3.addWidget(self.lb3)
        self.lb4 = QtWidgets.QLabel(loginForm)
        self.lb4.setObjectName("lb4")
        self.horizontalLayout_3.addWidget(self.lb4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.pushButton = QtWidgets.QPushButton(loginForm)
        self.pushButton.setIconSize(QtCore.QSize(16, 24))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout)

        self.retranslateUi(loginForm)
        QtCore.QMetaObject.connectSlotsByName(loginForm)

    def retranslateUi(self, loginForm):
        _translate = QtCore.QCoreApplication.translate
        loginForm.setWindowTitle(_translate("loginForm", "QQ登录客户端"))
        self.lb0.setText(_translate("loginForm", "QQ登录"))
        self.lb1.setText(_translate("loginForm", "用户"))
        self.username.setPlaceholderText(_translate("loginForm", "请输入用户"))
        self.lb2.setText(_translate("loginForm", "密码"))
        self.password.setPlaceholderText(_translate("loginForm", "请输入密码"))
        self.lb3.setText(_translate("loginForm", "<html><head/><body><p><a href=\"www.baidu.com\"><span style=\" text-decoration: underline; color:#0000ff;\">忘记密码</span></a></p></body></html>"))
        self.lb4.setText(_translate("loginForm", "<html><head/><body><p><a href=\"www.baidu.com\"><span style=\" text-decoration: underline; color:#0000ff;\">没有账号？</span></a></p></body></html>"))
        self.pushButton.setText(_translate("loginForm", "登录"))
