# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow,QDialog

'''自导入模块'''
from handle import handleEvent
from designer.mianForm import Ui_MainForm

class Ui_loginForm(object):
    def __init__(self):
       self.Form = None

    def setupUi(self, loginForm):
        # 获取当前窗体
        self.Form = loginForm
        loginForm.setObjectName("loginForm")
        loginForm.resize(423, 381)
        self.widget = QtWidgets.QWidget(loginForm)
        self.widget.setGeometry(QtCore.QRect(120, 30, 191, 181))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb1 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lb1.setFont(font)
        self.lb1.setAlignment(QtCore.Qt.AlignCenter)
        self.lb1.setObjectName("lb1")
        self.verticalLayout.addWidget(self.lb1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb2 = QtWidgets.QLabel(self.widget)
        self.lb2.setOpenExternalLinks(False)
        self.lb2.setObjectName("lb2")
        self.horizontalLayout.addWidget(self.lb2)
        self.userLine = QtWidgets.QLineEdit(self.widget)
        self.userLine.setObjectName("userLine")
        self.horizontalLayout.addWidget(self.userLine)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb3 = QtWidgets.QLabel(self.widget)
        self.lb3.setObjectName("lb3")
        self.horizontalLayout_2.addWidget(self.lb3)
        self.pwdLine = QtWidgets.QLineEdit(self.widget)
        self.pwdLine.setObjectName("pwdLine")
        self.horizontalLayout_2.addWidget(self.pwdLine)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb5 = QtWidgets.QLabel(self.widget)
        self.lb5.setOpenExternalLinks(True)
        self.lb5.setObjectName("lb5")
        self.horizontalLayout_3.addWidget(self.lb5)
        self.lb4 = QtWidgets.QLabel(self.widget)
        self.lb4.setOpenExternalLinks(True)
        self.lb4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.lb4.setObjectName("lb4")
        self.horizontalLayout_3.addWidget(self.lb4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.loginBT = QtWidgets.QPushButton(self.widget)
        self.loginBT.setObjectName("loginBT")
        self.verticalLayout.addWidget(self.loginBT)

        # 按钮事件
        # self.loginBT.clicked.connect(self.handleLoginBT)
        self.loginBT.clicked.connect(self.jumpForm)
        # self.loginBT.clicked.connect(lambda :self.handleLoginBT())

        self.retranslateUi(loginForm)
        QtCore.QMetaObject.connectSlotsByName(loginForm)

    def retranslateUi(self, loginForm):
        _translate = QtCore.QCoreApplication.translate
        loginForm.setWindowTitle(_translate("loginForm", "Form"))
        self.lb1.setText(_translate("loginForm", "QQ登录"))
        self.lb2.setText(_translate("loginForm", "用户"))
        self.userLine.setPlaceholderText(_translate("loginForm", "请输入用户名"))
        self.lb3.setText(_translate("loginForm", "密码"))
        self.pwdLine.setPlaceholderText(_translate("loginForm", "请输入密码"))
        self.lb5.setText(_translate("loginForm", "没有账号？"))
        self.lb4.setText(_translate("loginForm", "忘记密码"))
        self.loginBT.setText(_translate("loginForm", "登录"))

    def handleLoginBT(self):
        if handleEvent.handleLoginBT(self.userLine, self.pwdLine):
            self.jumpForm()
            # print("hello")

    def jumpForm(self):
        self.Form.hide()
        dialog1 = QDialog()
        mainForm = Ui_MainForm()
        mainForm.setupUi(dialog1)
        dialog1.show()
        dialog1.exec_()
        self.Form.show()

        # while True:
        #     print(handleEvent.handleLoginBT(self.userLine, self.pwdLine))
        #     if handleEvent.handleLoginBT(self.userLine,self.pwdLine):
        #         break


