# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(516, 446)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 421, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.qvOne = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.qvOne.setContentsMargins(0, 0, 0, 0)
        self.qvOne.setObjectName("qvOne")
        self.pTOne = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.pTOne.setObjectName("pTOne")
        self.qvOne.addWidget(self.pTOne)
        self.pBOne = QtWidgets.QPushButton(Form)
        self.pBOne.setGeometry(QtCore.QRect(200, 290, 75, 23))
        self.pBOne.setObjectName("pBOne")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QQ登录"))
        self.pTOne.setPlaceholderText(_translate("Form", "请输入对话内容"))
        self.pBOne.setText(_translate("Form", "提交"))
