# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(296, 447)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(MainForm)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.nameContent = QtWidgets.QLabel(MainForm)
        self.nameContent.setMaximumSize(QtCore.QSize(16777215, 30))
        self.nameContent.setText("")
        self.nameContent.setObjectName("nameContent")
        self.horizontalLayout_5.addWidget(self.nameContent)
        self.titlePicture = QtWidgets.QLabel(MainForm)
        self.titlePicture.setMaximumSize(QtCore.QSize(16777215, 30))
        self.titlePicture.setText("")
        self.titlePicture.setObjectName("titlePicture")
        self.horizontalLayout_5.addWidget(self.titlePicture)
        self.transferText = QtWidgets.QPlainTextEdit(MainForm)
        self.transferText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.transferText.setObjectName("transferText")
        self.horizontalLayout_5.addWidget(self.transferText)
        self.statusText = QtWidgets.QPlainTextEdit(MainForm)
        self.statusText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.statusText.setObjectName("statusText")
        self.horizontalLayout_5.addWidget(self.statusText)
        self.hiddenText = QtWidgets.QPlainTextEdit(MainForm)
        self.hiddenText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.hiddenText.setObjectName("hiddenText")
        self.horizontalLayout_5.addWidget(self.hiddenText)
        self.promptText = QtWidgets.QPlainTextEdit(MainForm)
        self.promptText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.promptText.setObjectName("promptText")
        self.horizontalLayout_5.addWidget(self.promptText)
        self.horizontalLayout_5.setStretch(0, 3)
        self.horizontalLayout_5.setStretch(1, 2)
        self.horizontalLayout_5.setStretch(2, 1)
        self.horizontalLayout_5.setStretch(3, 1)
        self.horizontalLayout_5.setStretch(4, 1)
        self.horizontalLayout_5.setStretch(5, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.tabWidget = QtWidgets.QTabWidget(MainForm)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setIconSize(QtCore.QSize(24, 16))
        self.tabWidget.setObjectName("tabWidget")
        self.message = QtWidgets.QWidget()
        self.message.setObjectName("message")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.message)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.message)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 248, 190))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(0, -1, -1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PText2 = QtWidgets.QPlainTextEdit(self.message)
        self.PText2.setStyleSheet("")
        self.PText2.setBackgroundVisible(False)
        self.PText2.setObjectName("PText2")
        self.horizontalLayout.addWidget(self.PText2)
        self.sendBT = QtWidgets.QPushButton(self.message)
        self.sendBT.setMaximumSize(QtCore.QSize(16777215, 80))
        self.sendBT.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: deepskyblue;\n"
"}")
        self.sendBT.setObjectName("sendBT")
        self.horizontalLayout.addWidget(self.sendBT)
        self.addBT = QtWidgets.QPushButton(self.message)
        self.addBT.setMaximumSize(QtCore.QSize(16777215, 80))
        self.addBT.setStyleSheet("QPushButton{\n"
"    font-size:16px;\n"
"    background: url(\"../images/add.png\");\n"
"    background-size:contain;\n"
"    border: 0px;\n"
"    background-size: cover;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: deepskyblue;\n"
"}")
        self.addBT.setObjectName("addBT")
        self.horizontalLayout.addWidget(self.addBT)
        self.horizontalLayout.setStretch(0, 6)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 18)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fileBT = QtWidgets.QPushButton(self.message)
        self.fileBT.setStyleSheet("QPushButton{\n"
"    boder-radius:8px;\n"
"}")
        self.fileBT.setObjectName("fileBT")
        self.horizontalLayout_4.addWidget(self.fileBT)
        self.pictureBT = QtWidgets.QPushButton(self.message)
        self.pictureBT.setStyleSheet("QPushButton{\n"
"    boder-radius:8px;\n"
"}")
        self.pictureBT.setObjectName("pictureBT")
        self.horizontalLayout_4.addWidget(self.pictureBT)
        self.movieBT = QtWidgets.QPushButton(self.message)
        self.movieBT.setStyleSheet("QPushButton{\n"
"    boder-radius:8px;\n"
"}")
        self.movieBT.setObjectName("movieBT")
        self.horizontalLayout_4.addWidget(self.movieBT)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.message, "")
        self.setting = QtWidgets.QWidget()
        self.setting.setObjectName("setting")
        self.layoutWidget = QtWidgets.QWidget(self.setting)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 30, 141, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.personBT = QtWidgets.QPushButton(self.layoutWidget)
        self.personBT.setStyleSheet("QPushButton{\n"
"    font-size: 16px;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: deepskyblue;\n"
"}")
        self.personBT.setObjectName("personBT")
        self.verticalLayout.addWidget(self.personBT)
        self.accountBT = QtWidgets.QPushButton(self.layoutWidget)
        self.accountBT.setStyleSheet("QPushButton{\n"
"    font-size: 16px;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: deepskyblue;\n"
"}")
        self.accountBT.setObjectName("accountBT")
        self.verticalLayout.addWidget(self.accountBT)
        self.changeBT = QtWidgets.QPushButton(self.layoutWidget)
        self.changeBT.setStyleSheet("QPushButton{\n"
"    font-size: 16px;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: deepskyblue;\n"
"}")
        self.changeBT.setObjectName("changeBT")
        self.verticalLayout.addWidget(self.changeBT)
        self.exitBT = QtWidgets.QPushButton(self.layoutWidget)
        self.exitBT.setStyleSheet("QPushButton{\n"
"    font-size: 16px;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: deepskyblue;\n"
"}")
        self.exitBT.setObjectName("exitBT")
        self.verticalLayout.addWidget(self.exitBT)
        self.tabWidget.addTab(self.setting, "")
        self.verticalLayout_4.addWidget(self.tabWidget)

        self.retranslateUi(MainForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "QQ主页面"))
        self.sendBT.setText(_translate("MainForm", "发送"))
        self.addBT.setText(_translate("MainForm", "+"))
        self.fileBT.setText(_translate("MainForm", "文件"))
        self.pictureBT.setText(_translate("MainForm", "图片"))
        self.movieBT.setText(_translate("MainForm", "视频"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.message), _translate("MainForm", "消息"))
        self.personBT.setText(_translate("MainForm", "个人中心"))
        self.accountBT.setText(_translate("MainForm", "账户安全"))
        self.changeBT.setText(_translate("MainForm", "切换账户"))
        self.exitBT.setText(_translate("MainForm", "退出"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setting), _translate("MainForm", "设置"))
