# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QGridLayout, QLabel,QApplication,QWidget
import sys

class Ui_Form(object):
    def __init__(self):
        self.count = 0
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(59, 30, 281, 161))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 277, 157))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(60, 220, 281, 64))
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.layout = QGridLayout(self.scrollAreaWidgetContents)
        self.plainTextEdit.textChanged.connect(self.generatorControl)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

    def generatorControl(self):
        self.layout.addWidget(QLabel("hello"),self.count,0)
        self.count += 1
        self.scrollAreaWidgetContents.setLayout(self.layout)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    widget = QWidget()
    form = Ui_Form()
    form.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())
